name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/basic/'

  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: './examples/complete/'

  firewall-with-isolated-rules:
   uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
   with:
    working_directory: './examples/firewall-with-isolated-rules/'
  
  firewall-with-public-ip-prefix:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
     working_directory: './examples/firewall-with-public-ip-prefix/'  
